name: Github Action Demo
on:  push
jobs:
  Example-Acions-Job:
    name: Exployring Github Actions  
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job trigger by ${{github.event_name}} event"
      - run: echo "This job is now running on a by ${{runner.os}} server hosted by github"
      - name: List files is the repository
        run: |
          ls ${{github.workspace}}
  Second-job: 
    runs-on: ubuntu-lastest
    needs: Example-Acions-Job
    steps:
      - run: echo "this job is now running on a ${{runner.os}} server hosted by github"
